# Generated by Django 5.1.1 on 2024-11-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0004_remove_user_employee_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationtype',
            name='sanction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
